(function(){"use strict";const l=window.SenLinApp;if(!l)return;const{routes:y,state:a,save:g,esc:p,tts:k,toast:v,pinyinHTML:b}=l,h=window.SenLin,i=t=>document.querySelector(t),M="https://cdn.jsdelivr.net/npm/hanzi-writer@3.7.3/dist/hanzi-writer.min.js";let f=null;function C(){return window.HanziWriter?Promise.resolve(window.HanziWriter):f||(f=new Promise((t,e)=>{const s=document.createElement("script");s.src=M,s.onload=()=>t(window.HanziWriter),s.onerror=()=>{f=null,e(new Error("Could not load the stroke-order library (offline?)"))},document.head.appendChild(s)}))}a.progress.writes=a.progress.writes||{total:0,chars:{}};async function $(t){const e=h.CHARACTERS.find(o=>o.h===t)||{h:t,p:"",m:""},s=i("#dialog"),r=i("#dialog-inner");r.innerHTML=`<div class="row between"><span class="eyebrow">Write it · stroke order</span><button class="btn btn-sm btn-ghost" data-close>✕</button></div>
      <div class="row" style="gap:1rem;align-items:flex-start;justify-content:center;flex-wrap:wrap">
        <div id="hw-box" class="hw-box"><div class="muted small" style="padding:6rem 0;text-align:center">loading…</div></div>
        <div class="stack" style="min-width:180px">
          <div><span class="hz" style="font-size:2.2rem">${p(e.h)}</span> <span class="py">${b(e.p)}</span><div class="muted small">${p(e.m)}</div></div>
          <button class="btn btn-primary" id="hw-animate">▶ Animate strokes</button>
          <button class="btn" id="hw-quiz">✍️ Draw it yourself</button>
          <label class="small muted"><input type="checkbox" id="hw-outline" checked> show outline while drawing</label>
          <div class="small muted" id="hw-status">Watch once, then draw each stroke in order. Wrong strokes shake; three misses show the stroke.</div>
          <div class="faint small">Written ${a.progress.writes.chars[t]||0}× before</div>
        </div></div>`,s.open||s.showModal();try{const o=await C(),w=i("#hw-box");w.innerHTML="";const u=getComputedStyle(document.documentElement).getPropertyValue("--accent").trim()||"#23623e",c=o.create(w,t,{width:260,height:260,padding:10,showOutline:!0,showCharacter:!0,strokeColor:u,radicalColor:"#c9973a",outlineColor:"rgba(128,128,128,.25)",drawingColor:u,drawingWidth:18,strokeAnimationSpeed:1,delayBetweenStrokes:250,showHintAfterMisses:3,highlightOnComplete:!0});i("#hw-animate").onclick=()=>{c.showCharacter(),c.animateCharacter()},i("#hw-quiz").onclick=()=>{const m=i("#hw-outline").checked;i("#hw-status").textContent="Draw stroke 1…",m?c.showOutline():c.hideOutline(),c.quiz({onCorrectStroke:d=>{i("#hw-status").textContent=`Stroke ${d.strokeNum+1} of ${d.strokesRemaining+d.strokeNum+1} ✓`},onMistake:d=>{i("#hw-status").textContent=`Not quite — ${d.mistakesOnStroke} miss${d.mistakesOnStroke>1?"es":""} on stroke ${d.strokeNum+1}`},onComplete:d=>{a.progress.writes.total++,a.progress.writes.chars[t]=(a.progress.writes.chars[t]||0)+1,g(),i("#hw-status").textContent=`Done — ${d.totalMistakes} mistake${d.totalMistakes===1?"":"s"}. ${d.totalMistakes===0?"完美！":"Again?"}`}})},c.animateCharacter()}catch(o){i("#hw-box").innerHTML=`<p class="small muted" style="padding:2rem">${p(o.message)}</p>`}}document.addEventListener("click",t=>{const e=t.target.closest("[data-write]");e&&$(e.dataset.write)}),l.openWriter=$;const A={1:"1st · high flat ˉ",2:"2nd · rising ˊ",3:"3rd · low dip ˇ",4:"4th · falling ˋ",5:"neutral · light"},n={mode:"single",item:null,answered:!1,right:0,total:0,streak:0};a.progress.tones=a.progress.tones||{total:0,right:0,best:0};function H(){const t=l.DAYS(),e=l.todayDay(),s=a.progress.completed;let r=h.learnedItems(t,Math.min(e,t.length)).filter(o=>s[o.day]);return r.filter(o=>o.type==="c").length<20&&(r=h.CHARACTERS.filter(o=>o.level===1).map(o=>({type:"c",ref:o}))),r}function x(){const t=H();if(n.mode==="single"){const e=t.filter(r=>r.type==="c"),s=e[Math.floor(Math.random()*e.length)].ref;n.item={text:s.h,p:s.p,m:s.m,answer:String(h.parsePinyin(s.p).tone),options:["1","2","3","4","5"]}}else{const e=t.filter(m=>m.type==="w"&&Array.from(m.ref.w).length===2),s=e[Math.floor(Math.random()*e.length)].ref,r=s.p.replace(/['’]/g," ").split(/\s+/).join(" "),w=E(s).join("-"),u=new Set([w]);let c=0;for(;u.size<4&&c++<50;)u.add(`${1+Math.floor(Math.random()*4)}-${1+Math.floor(Math.random()*4)}`);n.item={text:s.w,p:s.p,m:s.m,answer:w,options:Array.from(u).sort(()=>Math.random()-.5),syl:r}}n.answered=!1}function E(t){return Array.from(t.w).map(e=>{const s=h.CHARACTERS.find(r=>r.h===e);return s?h.parsePinyin(s.p).tone:5}).map(e=>e===5?5:e)}y.tones=function(){n.item||x();const t=n.item;return`<div class="stack-lg" style="max-width:640px">
      <div class="row between"><div><span class="eyebrow">Tone gym</span><h1 class="h2">Hear it, name the tone</h1></div>
        <div class="row"><button class="btn btn-sm${n.mode==="single"?" btn-primary":""}" data-mode="single">Single</button><button class="btn btn-sm${n.mode==="pair"?" btn-primary":""}" data-mode="pair">Tone pairs</button></div></div>
      <div class="card stack" style="text-align:center">
        <div class="row" style="justify-content:center"><button class="btn btn-lg btn-primary" data-say="${p(t.text)}">🔊 Play</button><button class="btn" data-say="${p(t.text)}" data-rate="0.6">🐢 Slow</button></div>
        <div class="big-hz" style="font-size:4rem;${n.answered?"":"filter:blur(14px);opacity:.5"}">${p(t.text)}</div>
        <div class="muted small">${n.answered?`<span class="py">${b(t.p)}</span> · ${p(t.m)}`:"Listen, then choose. The character is revealed after you answer."}</div>
        <div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(110px,1fr))">
          ${t.options.map(e=>`<button class="quiz-opt${n.answered&&e===t.answer?" right":""}" data-tone="${e}" style="text-align:center">${n.mode==="single"?p(A[e]):p(e)}</button>`).join("")}
        </div>
        ${n.answered?'<div class="row" style="justify-content:center"><button class="btn btn-primary" id="tone-next">Next →</button></div>':""}
      </div>
      <div class="row between small muted"><span>Session: ${n.right} / ${n.total} · streak ${n.streak}</span><span>All time: ${a.progress.tones.total?Math.round(a.progress.tones.right/a.progress.tones.total*100):0}% of ${a.progress.tones.total} · best streak ${a.progress.tones.best}</span></div>
      <p class="small muted">Why this matters: tone errors are the number-one reason learners are misunderstood. Ten reps a day here rewires the ear faster than any amount of reading.</p>
    </div>`},y.tones.after=()=>{document.querySelectorAll("[data-mode]").forEach(e=>e.onclick=()=>{n.mode=e.dataset.mode,n.item=null,l.navigate()}),document.querySelectorAll("[data-tone]").forEach(e=>e.onclick=()=>{if(n.answered)return;n.answered=!0,n.total++,a.progress.tones.total++;const s=e.dataset.tone===n.item.answer;s?(n.right++,n.streak++,a.progress.tones.right++,a.progress.tones.best=Math.max(a.progress.tones.best,n.streak)):(n.streak=0,e.classList.add("wrong")),g();const r=e;if(l.navigate(),!s){const o=document.querySelector(`[data-tone="${r.dataset.tone}"]`);o&&o.classList.add("wrong")}});const t=i("#tone-next");t&&(t.onclick=()=>{x(),l.navigate(),k.speak(n.item.text)}),document.addEventListener("keydown",S)};function S(t){if(!location.hash.startsWith("#/tones")){document.removeEventListener("keydown",S);return}if(t.target.matches("input,textarea"))return;t.key===" "&&(t.preventDefault(),k.speak(n.item.text));const e=document.querySelector(`[data-tone="${t.key}"]`);if(e&&n.mode==="single"&&e.click(),t.key==="Enter"){const s=i("#tone-next");s&&s.click()}}l.applyPlacement=function(t){const e=l.DAYS(),s=Date.now();let r=0;for(const o of e){const w=o.type==="pron",u=o.level||0;(w||u&&u<=t)&&(a.progress.completed[o.day]||(a.progress.completed[o.day]="skipped",r++),h.learnedItems([o],o.day).forEach(c=>{if(!a.srs[c.id]){const m=h.srsInit();m.reps=3,m.ivl=30,m.ef=2.5,m.due=s+(7+Math.floor(Math.random()*30))*864e5,a.srs[c.id]=m}}))}return a.settings.placement=t,g(),r},l.placementExtra=()=>`<section class="card stack">
      <h2 class="h3">Already know some Chinese?</h2>
      <p class="muted small">Mark everything up to a level as learned. Those days leave the catch-up queue and their characters, words and sentences enter your review deck on a gentle 1–5 week schedule, so gaps still surface.</p>
      <div class="row"><select class="input" id="placement" style="max-width:260px">${[0,1,2,3,4,5].map(t=>`<option value="${t}"${(a.settings.placement||0)===t?" selected":""}>${t===0?"Start from zero":`I know HSK ${t} (skip to HSK ${t+1})`}</option>`).join("")}</select><button class="btn" id="placement-apply">Apply</button></div>
    </section>`,l.placementExtraAfter=()=>{const t=i("#placement-apply");t&&(t.onclick=()=>{const e=+i("#placement").value;if(!e){a.settings.placement=0,g(),v("Placement cleared (progress kept)");return}if(!confirm(`Mark HSK 1–${e} as already learned?`))return;const s=l.applyPlacement(e);v(`${s} days marked learned · start at HSK ${e+1}`)})}})();
