#!/usr/bin/env node
/* Writes server/src/schedule.js: one [title, characters] pair per curriculum day, so the worker can
   personalise the daily reminder ("Day 14 · 我 你 他") without bundling the whole course.
     node tools/schedule.js            # prints whether the file is current (exit 1 when stale)
     node tools/schedule.js --write    # regenerates it (run after changing the curriculum or data)     */
'use strict';
const fs = require('fs');
const path = require('path');
const S = require('../js/engine.js');

const OUT = path.resolve(__dirname, '../server/src/schedule.js');
const days = S.buildSchedule();
const rows = days.map(d => d.type === 'pron' ? [d.pron.title, ''] : d.type === 'chars' ? [d.phase, d.chars.map(c => c.h).join(' ')] : [d.phase, '']);
const text = `// Generated by tools/schedule.js from the curriculum — do not edit. [title, characters] for each day, day 1 first.\nexport default ${JSON.stringify(rows)};\n`;

if (process.argv.includes('--write')) { fs.writeFileSync(OUT, text); console.log(`wrote ${path.relative(process.cwd(), OUT)}: ${rows.length} days`); }
else {
  const current = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === text;
  console.log(current ? `server/src/schedule.js is current (${rows.length} days)` : 'server/src/schedule.js is STALE — run: node tools/schedule.js --write');
  process.exit(current ? 0 : 1);
}
